# -*- coding: utf-8 -*-
"""Estructuras_ciclicas_while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZS-PksJ0opNQizPjVh0IM5_bOFF_Ohq

# WHILE

Un ciclo while ejecuta las instrucciones dentro de su cuerpor tantas veces como la condicion permenezca como True. Por tanto, cuando la condicion sea False saldra del ciclo. Vemos que el ciclo while utiliza un condicional para evaluar la condicion.

De antemano **NO** sabemos cuantas vecez se va a repetir el ciclo

Por ejemplo, en un juego de adivinanzas no sabemoS cauntas veces el usuario adivinarai, pero el juego continua mientras (while) este adivinando.

```
while condicion:
  #cuerpo del ciclo
```

Realice un algoritmo que imprima los primeros ```n``` naturales.
"""

n = int(input("Ingrese el entero: "))
i = 1

while (i<=n):
  print(i,"\t")
  i +=1

"""Realice un algoritmo que calcule ```n``` factorial."""

# respuesta

"""#WHILE INFINITOS

**Ejercicios:** Cual de los siguientes codigos resultará en un loop infinito?

1.   ```
      while True:
        print("Go Yellow Jackets!")
     ```
2.    ```
      x = 0
      while x < 5:
        x += 1
      ```
3.    ```
      x = 0
      while x < 5:
         x -= 1
      ```
4.    ```
      for i in range(0, Infinity):
        print(i)
      ```
"""

for i in range(0, 10):
  print(i)

"""Para evitar tener ciclo infinitos, debemos poner mucha atencion en la condicion del ciclo para que termine en algún punto.

#WHILE CON LISTAS
"""

lista = [1, 2, 3, 4]

while lista:                # Se ejecutara hasta que haya un elemento en la lista
  print("POP:   ",lista.pop())
  print("lista: ",lista)

print("Asi quedo la lista:",lista)

lista =  list(input("Ingrese la lista: ")) #ingrese: abcd
#lista =  ['a', 'b', 'c', 'd']
while lista:
  print(lista.pop())

"""# WHILE en una linea"""

i = 0
while (i<=5): i+=1; print(i)

list = [5,1,3, 2, 6]
list.remove(3)
print(list)

"""#CONTINUE AND BREAK

```continue```  salta y empieza una nueva iteración

```break``` termina la ejecución
"""

cadena = "Universidad"
i=0

while i<len(cadena):
  if cadena[i]=='i' or cadena[i]=='s':
    i+=1
    continue
  print(cadena[i])
  i+=1

print("Nos salimos del bucle")

cadena = "Universidad"
i=0

while i<len(cadena):
  if cadena[i]=='i':
    break
  print(cadena[i])
  i+=1

print("Nos salimos del bucle")