# -*- coding: utf-8 -*-
"""Estructuras_ciclicas_FOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keOuDtyBmaCvpIWFGzLbuu7vi6RlclRl

# FOR

Un ciclo FOR ejecuta las instrucciones dentro de su cuerpo un número finito (predeterminado) de veces. Por tanto, cuando la condicion sea False saldra del ciclo. Vemos que el ciclo while utiliza un condicional para evaluar la condicion.

Bucle: Una estructura de control de programación que ejecuta un segmento de código varias veces.


```
for variable in range(inicial, final, incremento):
  #cuerpo del ciclo
```
"""

for k in range(1,5,1):
  print(f"valor de k es {k}")     # formateamos la cadena, y con f indicamos que lo que este dentro de { } es una variable
  #print("valor de k es",k)

"""## Range()

`range(inicio, final, incremento)` es una función que devuelve una secuencia de números, empezando por 0 por defecto, y se incrementa en 1 (por defecto), y se detiene **antes** de un número especificado.

Imprimir los primeros k numeros a partir del número j con incremento i
"""

k=10; j=2; i =1
v = range(j,k+1,i)  # ¿ Por qué agrego hasta k+1?
for k in v:
  print(k)

"""¿ Qué tipo de dato es v?"""

type(v)
print(v)

i = 0
for k in range(10,1,-2):
  i = i+1
  print("En la iteracion: " +str(i) + " - el valor de k es: "+str(k))

"""# Listas con ciclo For

El ciclo/bucle for me sirve por ejemplo para procesar cada elemento de una lista
"""

lista = ['a', 'b', 'c', 'd']

for i in lista:
  print(i)

"""Considere la siguiente lista de enteros

Lista= [3, 5 , 6, 7]

Calcule el promedio usando un ciclo for
"""

# ejercicio

"""Cuando se itera sobre una secuencia, se puede obtener el índice de posición junto a su valor correspondiente usando la función enumerate()"""

lista = ['a', 'b', 'c', 'd']

for i,v in enumerate(lista):
  print(f"Indice: {i} - Valor: {v}")

"""Tambien podemos escribir el ciclo for en una linea, similar a como lo hicimos en el condicional"""

lista = [i for i in range(1,4)]
lista

lista_c = [i**2 for i in range(1,4)]
lista_c

"""Se puede borrar posiciones con del o toda la lista por completo"""

del lista_c[0]
lista_c

del lista_c
lista_c

"""# Sentencias (Statements) de control

## Break

La sentencia `break` me permite salir del bucle
"""

cadena = "Universidad"
for i in cadena:
  if i=='e':
    break
  print(i)

print("Nos salimos del bucle")

cadena = "Universidad"

for i in cadena:
  if i=='i':
    continue          # Cuando i es 4, salta las lineas de codigo que siguen y pasa ala siguiente iteración
  elif i=='a':
    continue          # Cuando i es 8, salta las lineas de codigo que siguen y pasa ala siguiente iteración
  print(i)