# -*- coding: utf-8 -*-
"""My_math_library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDd1EURHEi70xXE4wxBKWtozuN1yssVV
"""

# archivo: mi libreria math
def f_factorial(n):
    producto = 1
    for i in range(1, n + 1):
        producto *= i
    return producto

def f_sen(angulo):
    from math import pi
    Sold = 0
    Snew = 0
    E_max = 0.0000005
    E = E_max + 1
    angulo = angulo * pi / 180
    n = 1
    while E >= E_max:
        Snew = Sold + (((-1) ** (n + 1)) * (angulo ** (2 * n - 1))) / f_factorial(2 * n - 1)
        E = abs(Snew - Sold) / abs(Snew)
        Sold = Snew
        n += 1
    return Snew