# -*- coding: utf-8 -*-
"""valor_seno_series_taylor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cW86hrQvCXtX8stGQyAYG9Vg12hiwZ-
"""


from my_math_library import  f_factorial, f_sen

def hola():
    n = 1
    print(f_factorial(n))

    theta = 180
    print(f'seno de {theta} es = {f_sen(theta)}')
    theta = 60
    print(f'seno de {theta} es = {f_sen(theta)}')

if __name__ == "__main__":
    #hola()
    n = 1
    print(f_factorial(n))

    theta = 180
    print(f'seno de {theta} es = {f_sen(theta)}')
    theta = 60
    print(f'seno de {theta} es = {f_sen(theta)}')
    
    
    